version: '3.5'
services:
  react:
    build:
      context: ./services/react/
      dockerfile: Dockerfile
    image: shutterbug-react
    container_name: react
    restart: unless-stopped
    volumes:
    #      - ./services/react:/usr/src/app
      - ./services/react:/app:z  # z needed for selinux
      - /app/node_modules
      - /build/client
    env_file: .env
    environment:
      - NODE_ENV=production
  react-nginx:
    build:
      context: ./services/react-nginx/
      dockerfile: Dockerfile
    image: shutterbug-nginx
    container_name: shutterbug-nginx
    restart: always
    volumes:
      - ./services/react/build/client/:/client
    env_file: .env
    depends_on:
      - react
  reverseproxy:
    build:
      context: ./services/reverseproxy/
      dockerfile: Dockerfile
    image: shutterbug-proxy
    container_name: shutterbug-proxy
    restart: always
    ports:
      - 80:80 # react app
    depends_on:
      - react
      - react-nginx